# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\CSCI3280\project\sound_recording\UI\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(820, 790)
        mainWindow.setMinimumSize(QtCore.QSize(820, 790))
        mainWindow.setAcceptDrops(False)
        mainWindow.setStyleSheet("background-color:rgb(32, 32, 32);\n"
"color:white;")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setMinimumSize(QtCore.QSize(800, 600))
        self.frame.setStyleSheet("color:black;\n"
"background-color:rgb(250, 250, 250)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(100, 100))
        self.frame_4.setMaximumSize(QtCore.QSize(300, 99999))
        self.frame_4.setStyleSheet("background-color:rgb(32, 32, 32);\n"
"color:white;\n"
"border: thick white;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.AudioFileLayout_2 = QtWidgets.QVBoxLayout()
        self.AudioFileLayout_2.setSpacing(0)
        self.AudioFileLayout_2.setObjectName("AudioFileLayout_2")
        self.importFileBtn = QtWidgets.QPushButton(self.frame_4)
        self.importFileBtn.setMinimumSize(QtCore.QSize(100, 30))
        self.importFileBtn.setMaximumSize(QtCore.QSize(9999, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.importFileBtn.setFont(font)
        self.importFileBtn.setStyleSheet("QPushButton{\n"
"border-radius: 40px;\n"
"border: 1px solid white;\n"
"color:black;\n"
"background-color: rgba(255, 255, 255,200)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 255, 100)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.importFileBtn.setIconSize(QtCore.QSize(15, 15))
        self.importFileBtn.setObjectName("importFileBtn")
        self.AudioFileLayout_2.addWidget(self.importFileBtn)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.selectedFileName = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectedFileName.sizePolicy().hasHeightForWidth())
        self.selectedFileName.setSizePolicy(sizePolicy)
        self.selectedFileName.setMinimumSize(QtCore.QSize(50, 20))
        self.selectedFileName.setMaximumSize(QtCore.QSize(9999, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.selectedFileName.setFont(font)
        self.selectedFileName.setStyleSheet("")
        self.selectedFileName.setObjectName("selectedFileName")
        self.horizontalLayout_4.addWidget(self.selectedFileName)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.AudioFileLayout_2.addLayout(self.horizontalLayout_4)
        self.removeSelectedBtn = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeSelectedBtn.sizePolicy().hasHeightForWidth())
        self.removeSelectedBtn.setSizePolicy(sizePolicy)
        self.removeSelectedBtn.setMinimumSize(QtCore.QSize(100, 20))
        self.removeSelectedBtn.setMaximumSize(QtCore.QSize(9999, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.removeSelectedBtn.setFont(font)
        self.removeSelectedBtn.setStyleSheet("QPushButton{\n"
"border-radius: 40px;\n"
"border: 1px solid black;\n"
"background-color: rgba(255, 255, 255,200);\n"
"color:black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255,255, 100)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.removeSelectedBtn.setObjectName("removeSelectedBtn")
        self.AudioFileLayout_2.addWidget(self.removeSelectedBtn)
        self.audioFileList = QtWidgets.QListWidget(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.audioFileList.sizePolicy().hasHeightForWidth())
        self.audioFileList.setSizePolicy(sizePolicy)
        self.audioFileList.setMinimumSize(QtCore.QSize(100, 600))
        self.audioFileList.setMaximumSize(QtCore.QSize(300, 800))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.audioFileList.setFont(font)
        self.audioFileList.setStyleSheet(" QListView::item {\n"
"    background-color:rgb(76, 76, 76);\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(32, 32, 32,200);\n"
" }\n"
"\n"
" QListView::item:selected {\n"
"     border-left: 5px solid rgb(226, 75, 0);\n"
"    color: white;\n"
" }\n"
"\n"
" QListView::item:selected:!active {\n"
"     color: white;\n"
" }\n"
"\n"
" QListView::item:hover {\n"
"     background: rgb(100, 100, 100);\n"
"    color: white;\n"
" }")
        self.audioFileList.setEditTriggers(QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.audioFileList.setMovement(QtWidgets.QListView.Static)
        self.audioFileList.setFlow(QtWidgets.QListView.TopToBottom)
        self.audioFileList.setProperty("isWrapping", False)
        self.audioFileList.setViewMode(QtWidgets.QListView.ListMode)
        self.audioFileList.setModelColumn(0)
        self.audioFileList.setUniformItemSizes(True)
        self.audioFileList.setWordWrap(True)
        self.audioFileList.setSelectionRectVisible(True)
        self.audioFileList.setObjectName("audioFileList")
        self.AudioFileLayout_2.addWidget(self.audioFileList)
        self.verticalLayout_8.addLayout(self.AudioFileLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.tap = QtWidgets.QTabWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tap.sizePolicy().hasHeightForWidth())
        self.tap.setSizePolicy(sizePolicy)
        self.tap.setMinimumSize(QtCore.QSize(300, 200))
        self.tap.setMaximumSize(QtCore.QSize(16777215, 9999))
        self.tap.setStyleSheet("/* below style sheet is from default Qt Design*/\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"     border-top: 2px solid #C2C7CB;\n"
" }\n"
"\n"
" QTabWidget::tab-bar {\n"
"     left: 5px; /* move to the right by 5px */\n"
" }\n"
"\n"
" /* Style the tab using the tab sub-control. Note that\n"
"     it reads QTabBar _not_ QTabWidget */\n"
" QTabBar::tab {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"     border: 2px solid #C4C4C3;\n"
"     border-bottom-color: #C2C7CB; /* same as the pane color */\n"
"     border-top-left-radius: 4px;\n"
"     border-top-right-radius: 4px;\n"
"     min-width: 8ex;\n"
"     padding: 2px;\n"
" }\n"
"\n"
" QTabBar::tab:selected, QTabBar::tab:hover {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
" }\n"
"\n"
" QTabBar::tab:selected {\n"
"     border-color: #9B9B9B;\n"
"     border-bottom-color: #C2C7CB; /* same as pane color */\n"
" }\n"
"\n"
" QTabBar::tab:!selected {\n"
"     margin-top: 2px; /* make non-selected tabs look smaller */\n"
" }")
        self.tap.setTabPosition(QtWidgets.QTabWidget.North)
        self.tap.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tap.setIconSize(QtCore.QSize(30, 30))
        self.tap.setElideMode(QtCore.Qt.ElideMiddle)
        self.tap.setUsesScrollButtons(False)
        self.tap.setMovable(False)
        self.tap.setTabBarAutoHide(False)
        self.tap.setObjectName("tap")
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setObjectName("mainPage")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.mainPage)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_5 = QtWidgets.QFrame(self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AudioTitle = QtWidgets.QLabel(self.frame_5)
        self.AudioTitle.setMinimumSize(QtCore.QSize(500, 40))
        self.AudioTitle.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.AudioTitle.setFont(font)
        self.AudioTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.AudioTitle.setObjectName("AudioTitle")
        self.horizontalLayout.addWidget(self.AudioTitle)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(100, 100))
        self.label_4.setMaximumSize(QtCore.QSize(100, 100))
        self.label_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_4.setBaseSize(QtCore.QSize(0, 0))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/music_cover.jpeg"))
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.speech2text = QtWidgets.QLabel(self.frame_5)
        self.speech2text.setMinimumSize(QtCore.QSize(0, 30))
        self.speech2text.setMaximumSize(QtCore.QSize(1000, 27))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.speech2text.setFont(font)
        self.speech2text.setObjectName("speech2text")
        self.verticalLayout_10.addWidget(self.speech2text)
        self.mainAudioVisual = QtWidgets.QWidget(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainAudioVisual.sizePolicy().hasHeightForWidth())
        self.mainAudioVisual.setSizePolicy(sizePolicy)
        self.mainAudioVisual.setMinimumSize(QtCore.QSize(600, 140))
        self.mainAudioVisual.setMaximumSize(QtCore.QSize(9999, 9999))
        self.mainAudioVisual.setSizeIncrement(QtCore.QSize(0, 100))
        self.mainAudioVisual.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.mainAudioVisual.setObjectName("mainAudioVisual")
        self.verticalLayout_10.addWidget(self.mainAudioVisual)
        self.hoverSecond = QtWidgets.QLabel(self.frame_5)
        self.hoverSecond.setMinimumSize(QtCore.QSize(100, 11))
        self.hoverSecond.setMaximumSize(QtCore.QSize(100, 11))
        self.hoverSecond.setSizeIncrement(QtCore.QSize(0, 0))
        self.hoverSecond.setObjectName("hoverSecond")
        self.verticalLayout_10.addWidget(self.hoverSecond)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem4)
        self.verticalLayout_9.addWidget(self.frame_5)
        self.tap.addTab(self.mainPage, "")
        self.Recording = QtWidgets.QWidget()
        self.Recording.setObjectName("Recording")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Recording)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.recordTimeTitle = QtWidgets.QLabel(self.Recording)
        self.recordTimeTitle.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.recordTimeTitle.setFont(font)
        self.recordTimeTitle.setObjectName("recordTimeTitle")
        self.verticalLayout_5.addWidget(self.recordTimeTitle)
        self.recordTime = QtWidgets.QLabel(self.Recording)
        self.recordTime.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.recordTime.setFont(font)
        self.recordTime.setObjectName("recordTime")
        self.verticalLayout_5.addWidget(self.recordTime)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.recordBtn = QtWidgets.QPushButton(self.Recording)
        self.recordBtn.setMinimumSize(QtCore.QSize(80, 80))
        self.recordBtn.setMaximumSize(QtCore.QSize(80, 80))
        self.recordBtn.setStyleSheet("QPushButton{\n"
"border-radius: 40px;\n"
"border: 1px solid black;\n"
"background-color: rgba(255, 10, 0,200)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 10, 0, 100)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 10, 0)\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: rgb(145, 145, 145)\n"
"}")
        self.recordBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/tap/recording.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.recordBtn.setIcon(icon)
        self.recordBtn.setIconSize(QtCore.QSize(80, 80))
        self.recordBtn.setObjectName("recordBtn")
        self.horizontalLayout_5.addWidget(self.recordBtn)
        self.pauseRecBtn = QtWidgets.QPushButton(self.Recording)
        self.pauseRecBtn.setEnabled(False)
        self.pauseRecBtn.setMinimumSize(QtCore.QSize(80, 80))
        self.pauseRecBtn.setMaximumSize(QtCore.QSize(80, 80))
        self.pauseRecBtn.setStyleSheet("QPushButton{\n"
"border-radius: 40px;\n"
"border: 1px solid black;\n"
"background-color: rgba(255, 255, 0,200)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 0, 100)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 255, 0)\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: rgb(145, 145, 145)\n"
"}\n"
"\n"
"")
        self.pauseRecBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pauseRecBtn.setIcon(icon1)
        self.pauseRecBtn.setIconSize(QtCore.QSize(40, 40))
        self.pauseRecBtn.setObjectName("pauseRecBtn")
        self.horizontalLayout_5.addWidget(self.pauseRecBtn)
        self.saveRecBtn = QtWidgets.QPushButton(self.Recording)
        self.saveRecBtn.setEnabled(False)
        self.saveRecBtn.setMinimumSize(QtCore.QSize(80, 80))
        self.saveRecBtn.setMaximumSize(QtCore.QSize(80, 80))
        self.saveRecBtn.setStyleSheet("QPushButton{\n"
"border-radius: 40px;\n"
"border: 1px solid black;\n"
"background-color: rgba(255, 10, 0,200)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 10, 0, 100)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 10, 0)\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: rgb(145, 145, 145)\n"
"}\n"
"\n"
"")
        self.saveRecBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.saveRecBtn.setIcon(icon2)
        self.saveRecBtn.setIconSize(QtCore.QSize(40, 40))
        self.saveRecBtn.setObjectName("saveRecBtn")
        self.horizontalLayout_5.addWidget(self.saveRecBtn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.label_15 = QtWidgets.QLabel(self.Recording)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.recordMessage = QtWidgets.QLabel(self.Recording)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.recordMessage.setFont(font)
        self.recordMessage.setText("")
        self.recordMessage.setObjectName("recordMessage")
        self.verticalLayout_5.addWidget(self.recordMessage)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.tap.addTab(self.Recording, "")
        self.Editing = QtWidgets.QWidget()
        self.Editing.setMaximumSize(QtCore.QSize(794, 565))
        self.Editing.setObjectName("Editing")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Editing)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 7)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.audioInfoTitle = QtWidgets.QLabel(self.Editing)
        self.audioInfoTitle.setMinimumSize(QtCore.QSize(100, 20))
        self.audioInfoTitle.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.audioInfoTitle.setFont(font)
        self.audioInfoTitle.setObjectName("audioInfoTitle")
        self.verticalLayout_6.addWidget(self.audioInfoTitle)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.Editing)
        self.label_9.setMinimumSize(QtCore.QSize(140, 20))
        self.label_9.setMaximumSize(QtCore.QSize(140, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.editFileName = QtWidgets.QLineEdit(self.Editing)
        self.editFileName.setEnabled(False)
        self.editFileName.setMinimumSize(QtCore.QSize(200, 20))
        self.editFileName.setMaximumSize(QtCore.QSize(200, 20))
        self.editFileName.setObjectName("editFileName")
        self.gridLayout.addWidget(self.editFileName, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.Editing)
        self.label_11.setMinimumSize(QtCore.QSize(140, 20))
        self.label_11.setMaximumSize(QtCore.QSize(140, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.editDuration = QtWidgets.QLineEdit(self.Editing)
        self.editDuration.setEnabled(False)
        self.editDuration.setMinimumSize(QtCore.QSize(200, 20))
        self.editDuration.setMaximumSize(QtCore.QSize(200, 20))
        self.editDuration.setObjectName("editDuration")
        self.gridLayout.addWidget(self.editDuration, 1, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.editingTitle = QtWidgets.QLabel(self.Editing)
        self.editingTitle.setMinimumSize(QtCore.QSize(100, 20))
        self.editingTitle.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.editingTitle.setFont(font)
        self.editingTitle.setObjectName("editingTitle")
        self.verticalLayout_6.addWidget(self.editingTitle)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.Editing)
        self.label_13.setMinimumSize(QtCore.QSize(120, 20))
        self.label_13.setMaximumSize(QtCore.QSize(300, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        self.editStartingTime = QtWidgets.QLineEdit(self.Editing)
        self.editStartingTime.setEnabled(True)
        self.editStartingTime.setMinimumSize(QtCore.QSize(100, 20))
        self.editStartingTime.setMaximumSize(QtCore.QSize(100, 20))
        self.editStartingTime.setStyleSheet("border-radius: 40px;\n"
"border: 1px solid black;")
        self.editStartingTime.setObjectName("editStartingTime")
        self.horizontalLayout_6.addWidget(self.editStartingTime)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.editStartingTimeSlider = QtWidgets.QSlider(self.Editing)
        self.editStartingTimeSlider.setMinimumSize(QtCore.QSize(600, 20))
        self.editStartingTimeSlider.setMaximumSize(QtCore.QSize(600, 20))
        self.editStartingTimeSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 15px; \n"
"    background: rgb(255, 255, 255);\n"
"    border-radius:3px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background:  rgb(0, 0, 0);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 10px;\n"
"    margin: -5px 0;\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"\n"
" QSlider::add-page:horizontal {\n"
"     background: rgba(255, 255, 255, 10);\n"
" }\n"
"\n"
" QSlider::sub-page:horizontal {\n"
"     background: rgab(0, 0, 0, 200);\n"
" }")
        self.editStartingTimeSlider.setMaximum(999)
        self.editStartingTimeSlider.setPageStep(0)
        self.editStartingTimeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.editStartingTimeSlider.setObjectName("editStartingTimeSlider")
        self.verticalLayout_6.addWidget(self.editStartingTimeSlider)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.Editing)
        self.label_14.setMinimumSize(QtCore.QSize(120, 20))
        self.label_14.setMaximumSize(QtCore.QSize(300, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.editEndingTime = QtWidgets.QLineEdit(self.Editing)
        self.editEndingTime.setEnabled(True)
        self.editEndingTime.setMinimumSize(QtCore.QSize(100, 20))
        self.editEndingTime.setMaximumSize(QtCore.QSize(100, 20))
        self.editEndingTime.setStyleSheet("border-radius: 40px;\n"
"border: 1px solid black;")
        self.editEndingTime.setObjectName("editEndingTime")
        self.horizontalLayout_7.addWidget(self.editEndingTime)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.editEndingTimeSlider = QtWidgets.QSlider(self.Editing)
        self.editEndingTimeSlider.setMinimumSize(QtCore.QSize(600, 20))
        self.editEndingTimeSlider.setMaximumSize(QtCore.QSize(600, 20))
        self.editEndingTimeSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 15px; \n"
"    background: rgb(255, 255, 255);\n"
"    border-radius:3px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background:  rgb(0, 0, 0);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 10px;\n"
"    margin: -5px 0;\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"\n"
" QSlider::add-page:horizontal {\n"
"     background: rgba(255, 255, 255, 10);\n"
" }\n"
"\n"
" QSlider::sub-page:horizontal {\n"
"     background: rgab(0, 0, 0, 200);\n"
" }")
        self.editEndingTimeSlider.setMaximum(999)
        self.editEndingTimeSlider.setPageStep(0)
        self.editEndingTimeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.editEndingTimeSlider.setObjectName("editEndingTimeSlider")
        self.verticalLayout_6.addWidget(self.editEndingTimeSlider)
        self.editingTitle_2 = QtWidgets.QLabel(self.Editing)
        self.editingTitle_2.setMinimumSize(QtCore.QSize(100, 30))
        self.editingTitle_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.editingTitle_2.setFont(font)
        self.editingTitle_2.setObjectName("editingTitle_2")
        self.verticalLayout_6.addWidget(self.editingTitle_2)
        self.editingMessage = QtWidgets.QLabel(self.Editing)
        self.editingMessage.setMinimumSize(QtCore.QSize(400, 30))
        self.editingMessage.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.editingMessage.setFont(font)
        self.editingMessage.setText("")
        self.editingMessage.setObjectName("editingMessage")
        self.verticalLayout_6.addWidget(self.editingMessage)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.cutAndSaveBtn = QtWidgets.QPushButton(self.Editing)
        self.cutAndSaveBtn.setMinimumSize(QtCore.QSize(40, 30))
        self.cutAndSaveBtn.setStyleSheet("QPushButton{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"     border: 2px solid #C4C4C3;\n"
"     border-radius: 4px;\n"
"     min-width: 8ex;\n"
"     padding: 2px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #e7e7e7, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #eeeeee, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"")
        self.cutAndSaveBtn.setObjectName("cutAndSaveBtn")
        self.horizontalLayout_8.addWidget(self.cutAndSaveBtn)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.label_7 = QtWidgets.QLabel(self.Editing)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.Editing)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.editRecordBtn = QtWidgets.QPushButton(self.Editing)
        self.editRecordBtn.setMinimumSize(QtCore.QSize(80, 80))
        self.editRecordBtn.setMaximumSize(QtCore.QSize(80, 80))
        self.editRecordBtn.setStyleSheet("QPushButton{\n"
"border-radius: 40px;\n"
"border: 1px solid black;\n"
"background-color: rgba(255, 10, 0,200)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 10, 0, 100)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 10, 0)\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: rgb(145, 145, 145)\n"
"}")
        self.editRecordBtn.setText("")
        self.editRecordBtn.setIcon(icon)
        self.editRecordBtn.setIconSize(QtCore.QSize(80, 80))
        self.editRecordBtn.setObjectName("editRecordBtn")
        self.horizontalLayout_10.addWidget(self.editRecordBtn)
        self.editPauseRecBtn = QtWidgets.QPushButton(self.Editing)
        self.editPauseRecBtn.setEnabled(False)
        self.editPauseRecBtn.setMinimumSize(QtCore.QSize(80, 80))
        self.editPauseRecBtn.setMaximumSize(QtCore.QSize(80, 80))
        self.editPauseRecBtn.setStyleSheet("QPushButton{\n"
"border-radius: 40px;\n"
"border: 1px solid black;\n"
"background-color: rgba(255, 255, 0,200)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 0, 100)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 255, 0)\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: rgb(145, 145, 145)\n"
"}\n"
"\n"
"")
        self.editPauseRecBtn.setText("")
        self.editPauseRecBtn.setIcon(icon1)
        self.editPauseRecBtn.setIconSize(QtCore.QSize(40, 40))
        self.editPauseRecBtn.setObjectName("editPauseRecBtn")
        self.horizontalLayout_10.addWidget(self.editPauseRecBtn)
        self.editStopRecBtn = QtWidgets.QPushButton(self.Editing)
        self.editStopRecBtn.setEnabled(False)
        self.editStopRecBtn.setMinimumSize(QtCore.QSize(80, 80))
        self.editStopRecBtn.setMaximumSize(QtCore.QSize(80, 80))
        self.editStopRecBtn.setStyleSheet("QPushButton{\n"
"border-radius: 40px;\n"
"border: 1px solid black;\n"
"background-color: rgba(255, 10, 0,200)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 10, 0, 100)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 10, 0)\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: rgb(145, 145, 145)\n"
"}\n"
"\n"
"")
        self.editStopRecBtn.setText("")
        self.editStopRecBtn.setIcon(icon2)
        self.editStopRecBtn.setIconSize(QtCore.QSize(40, 40))
        self.editStopRecBtn.setObjectName("editStopRecBtn")
        self.horizontalLayout_10.addWidget(self.editStopRecBtn)
        self.editRecordTime = QtWidgets.QLabel(self.Editing)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.editRecordTime.setFont(font)
        self.editRecordTime.setObjectName("editRecordTime")
        self.horizontalLayout_10.addWidget(self.editRecordTime)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.overwriteBtn = QtWidgets.QPushButton(self.Editing)
        self.overwriteBtn.setEnabled(False)
        self.overwriteBtn.setMinimumSize(QtCore.QSize(40, 30))
        self.overwriteBtn.setStyleSheet("QPushButton:disabled,\n"
"button[disabled]{\n"
"  border: 1px solid #999999;\n"
"  background-color: #cccccc;\n"
"  color: #666666;\n"
"}\n"
"\n"
"QPushButton{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"     border: 2px solid #C4C4C3;\n"
"     border-radius: 4px;\n"
"     min-width: 8ex;\n"
"     padding: 2px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #e7e7e7, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #eeeeee, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"\n"
"")
        self.overwriteBtn.setObjectName("overwriteBtn")
        self.horizontalLayout_9.addWidget(self.overwriteBtn)
        self.label_6 = QtWidgets.QLabel(self.Editing)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.importCoverFIle = QtWidgets.QPushButton(self.Editing)
        self.importCoverFIle.setMinimumSize(QtCore.QSize(40, 30))
        self.importCoverFIle.setStyleSheet("QPushButton{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"     border: 2px solid #C4C4C3;\n"
"     border-radius: 4px;\n"
"     min-width: 8ex;\n"
"     padding: 2px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #e7e7e7, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #eeeeee, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"")
        self.importCoverFIle.setObjectName("importCoverFIle")
        self.horizontalLayout_9.addWidget(self.importCoverFIle)
        self.label_12 = QtWidgets.QLabel(self.Editing)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.owTips = QtWidgets.QLabel(self.Editing)
        self.owTips.setMinimumSize(QtCore.QSize(200, 0))
        self.owTips.setMaximumSize(QtCore.QSize(200, 16777215))
        self.owTips.setObjectName("owTips")
        self.horizontalLayout_9.addWidget(self.owTips)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem12)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.tap.addTab(self.Editing, "")
        self.enhancement = QtWidgets.QWidget()
        self.enhancement.setObjectName("enhancement")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.enhancement)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.enc_message = QtWidgets.QLabel(self.enhancement)
        self.enc_message.setMinimumSize(QtCore.QSize(0, 15))
        self.enc_message.setMaximumSize(QtCore.QSize(16777215, 15))
        self.enc_message.setObjectName("enc_message")
        self.verticalLayout_11.addWidget(self.enc_message)
        self.audioInfoTitle_2 = QtWidgets.QLabel(self.enhancement)
        self.audioInfoTitle_2.setMinimumSize(QtCore.QSize(100, 30))
        self.audioInfoTitle_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.audioInfoTitle_2.setFont(font)
        self.audioInfoTitle_2.setObjectName("audioInfoTitle_2")
        self.verticalLayout_11.addWidget(self.audioInfoTitle_2)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pitchValue = QtWidgets.QLineEdit(self.enhancement)
        self.pitchValue.setMinimumSize(QtCore.QSize(150, 30))
        self.pitchValue.setMaximumSize(QtCore.QSize(150, 30))
        self.pitchValue.setObjectName("pitchValue")
        self.horizontalLayout_13.addWidget(self.pitchValue)
        self.pitchChange = QtWidgets.QPushButton(self.enhancement)
        self.pitchChange.setMinimumSize(QtCore.QSize(40, 30))
        self.pitchChange.setMaximumSize(QtCore.QSize(100, 30))
        self.pitchChange.setStyleSheet("QPushButton{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"     border: 2px solid #C4C4C3;\n"
"     border-radius: 4px;\n"
"     min-width: 8ex;\n"
"     padding: 2px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #e7e7e7, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #eeeeee, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"")
        self.pitchChange.setObjectName("pitchChange")
        self.horizontalLayout_13.addWidget(self.pitchChange)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem13)
        self.verticalLayout_11.addLayout(self.horizontalLayout_13)
        self.label_3 = QtWidgets.QLabel(self.enhancement)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_11.addWidget(self.label_3)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.noiseRemoveBtn = QtWidgets.QPushButton(self.enhancement)
        self.noiseRemoveBtn.setMinimumSize(QtCore.QSize(40, 30))
        self.noiseRemoveBtn.setStyleSheet("QPushButton{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"     border: 2px solid #C4C4C3;\n"
"     border-radius: 4px;\n"
"     min-width: 8ex;\n"
"     padding: 2px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #e7e7e7, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #eeeeee, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"")
        self.noiseRemoveBtn.setObjectName("noiseRemoveBtn")
        self.horizontalLayout_14.addWidget(self.noiseRemoveBtn)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem14)
        self.verticalLayout_11.addLayout(self.horizontalLayout_14)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem15)
        self.tap.addTab(self.enhancement, "")
        self.Setting = QtWidgets.QWidget()
        self.Setting.setMinimumSize(QtCore.QSize(791, 557))
        self.Setting.setMaximumSize(QtCore.QSize(99999, 9999))
        self.Setting.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Setting.setStyleSheet("")
        self.Setting.setObjectName("Setting")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Setting)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.Setting)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.audioInputDriver = QtWidgets.QComboBox(self.frame_2)
        self.audioInputDriver.setMinimumSize(QtCore.QSize(500, 30))
        self.audioInputDriver.setMaximumSize(QtCore.QSize(500, 30))
        self.audioInputDriver.setObjectName("audioInputDriver")
        self.verticalLayout_3.addWidget(self.audioInputDriver, 0, QtCore.Qt.AlignTop)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.SavingPath = QtWidgets.QLineEdit(self.frame_2)
        self.SavingPath.setEnabled(False)
        self.SavingPath.setMinimumSize(QtCore.QSize(300, 10))
        self.SavingPath.setMaximumSize(QtCore.QSize(600, 300))
        self.SavingPath.setObjectName("SavingPath")
        self.verticalLayout_3.addWidget(self.SavingPath)
        self.SavingPathEdit = QtWidgets.QPushButton(self.frame_2)
        self.SavingPathEdit.setMinimumSize(QtCore.QSize(40, 30))
        self.SavingPathEdit.setMaximumSize(QtCore.QSize(300, 30))
        self.SavingPathEdit.setStyleSheet("QPushButton{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"     border: 2px solid #C4C4C3;\n"
"     border-radius: 4px;\n"
"     min-width: 8ex;\n"
"     padding: 2px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #e7e7e7, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #eeeeee, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"")
        self.SavingPathEdit.setObjectName("SavingPathEdit")
        self.verticalLayout_3.addWidget(self.SavingPathEdit)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem16)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.tap.addTab(self.Setting, "")
        self.horizontalLayout_2.addWidget(self.tap)
        self.verticalLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setStyleSheet("background-color:rgb(32, 32, 32);\n"
"border-top: thick white;\n"
"color:white;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.playerBarLayout_2 = QtWidgets.QVBoxLayout()
        self.playerBarLayout_2.setSpacing(5)
        self.playerBarLayout_2.setObjectName("playerBarLayout_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.currentTime = QtWidgets.QLabel(self.frame_3)
        self.currentTime.setMinimumSize(QtCore.QSize(100, 20))
        self.currentTime.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.currentTime.setFont(font)
        self.currentTime.setStyleSheet("color:white")
        self.currentTime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.currentTime.setObjectName("currentTime")
        self.horizontalLayout_11.addWidget(self.currentTime)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem17)
        self.endTime = QtWidgets.QLabel(self.frame_3)
        self.endTime.setMinimumSize(QtCore.QSize(100, 20))
        self.endTime.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.endTime.setFont(font)
        self.endTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.endTime.setAutoFillBackground(False)
        self.endTime.setStyleSheet("color:white")
        self.endTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.endTime.setObjectName("endTime")
        self.horizontalLayout_11.addWidget(self.endTime)
        self.playerBarLayout_2.addLayout(self.horizontalLayout_11)
        self.audioProgBar = QtWidgets.QSlider(self.frame_3)
        self.audioProgBar.setMinimumSize(QtCore.QSize(0, 20))
        self.audioProgBar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.audioProgBar.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 15px; \n"
"    background: rgb(255, 255, 255);\n"
"    border-radius:3px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background:  rgb(255, 255, 255);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 10px;\n"
"    margin: -1px -2px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
" QSlider::add-page:horizontal {\n"
"     background: rgba(35, 35, 35, 100);\n"
" }\n"
"\n"
" QSlider::sub-page:horizontal {\n"
"     background: rgab(0, 0, 0, 200);\n"
" }")
        self.audioProgBar.setMaximum(999)
        self.audioProgBar.setSingleStep(1)
        self.audioProgBar.setPageStep(0)
        self.audioProgBar.setProperty("value", 0)
        self.audioProgBar.setTracking(True)
        self.audioProgBar.setOrientation(QtCore.Qt.Horizontal)
        self.audioProgBar.setInvertedAppearance(False)
        self.audioProgBar.setInvertedControls(False)
        self.audioProgBar.setObjectName("audioProgBar")
        self.playerBarLayout_2.addWidget(self.audioProgBar)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem18)
        self.pauseBtn = QtWidgets.QPushButton(self.frame_3)
        self.pauseBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.pauseBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.pauseBtn.setStyleSheet("QPushButton{\n"
"border-radius: 40px;\n"
"border: 1px solid rgba(32, 32, 32,200);\n"
"background-color: rgba(32, 32, 32,200)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 255, 100)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(255, 255, 255, 150)\n"
"}\n"
"\n"
"")
        self.pauseBtn.setText("")
        self.pauseBtn.setIcon(icon1)
        self.pauseBtn.setIconSize(QtCore.QSize(25, 25))
        self.pauseBtn.setObjectName("pauseBtn")
        self.horizontalLayout_12.addWidget(self.pauseBtn)
        self.playBtn = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playBtn.sizePolicy().hasHeightForWidth())
        self.playBtn.setSizePolicy(sizePolicy)
        self.playBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.playBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.playBtn.setStyleSheet("QPushButton{\n"
"border-radius: 40px;\n"
"border: 1px solid black;\n"
"background-color: rgba(0, 255, 100,150)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(0, 255, 100, 180)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(0, 255, 100, 200)\n"
"}\n"
"\n"
"")
        self.playBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.playBtn.setIcon(icon3)
        self.playBtn.setIconSize(QtCore.QSize(25, 25))
        self.playBtn.setObjectName("playBtn")
        self.horizontalLayout_12.addWidget(self.playBtn)
        self.stopBtn = QtWidgets.QPushButton(self.frame_3)
        self.stopBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.stopBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.stopBtn.setStyleSheet("QPushButton{\n"
"border-radius: 40px;\n"
"border: 1px solid rgba(32, 32, 32,200);\n"
"background-color: rgba(32, 32, 32,200)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 255, 100)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(255, 255, 255, 150)\n"
"}\n"
"\n"
"")
        self.stopBtn.setText("")
        self.stopBtn.setIcon(icon2)
        self.stopBtn.setIconSize(QtCore.QSize(30, 30))
        self.stopBtn.setObjectName("stopBtn")
        self.horizontalLayout_12.addWidget(self.stopBtn)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem19)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        self.speedControl = QtWidgets.QComboBox(self.frame_3)
        self.speedControl.setMinimumSize(QtCore.QSize(113, 0))
        self.speedControl.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.speedControl.setFont(font)
        self.speedControl.setStyleSheet(" QComboBox {\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"    color:white;\n"
"    background-color:rgb(40, 40, 40);\n"
" }\n"
"\n"
"")
        self.speedControl.setObjectName("speedControl")
        self.speedControl.addItem("")
        self.speedControl.addItem("")
        self.speedControl.addItem("")
        self.speedControl.addItem("")
        self.speedControl.addItem("")
        self.speedControl.addItem("")
        self.horizontalLayout_12.addWidget(self.speedControl)
        self.playerBarLayout_2.addLayout(self.horizontalLayout_12)
        self.playerMessage = QtWidgets.QLabel(self.frame_3)
        self.playerMessage.setMinimumSize(QtCore.QSize(1024, 20))
        self.playerMessage.setMaximumSize(QtCore.QSize(99999, 20))
        self.playerMessage.setStyleSheet("QLabel{\n"
"background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255)\n"
"}")
        self.playerMessage.setObjectName("playerMessage")
        self.playerBarLayout_2.addWidget(self.playerMessage)
        self.verticalLayout_7.addLayout(self.playerBarLayout_2)
        self.verticalLayout.addWidget(self.frame_3)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 26))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.tap.setCurrentIndex(0)
        self.speedControl.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "G12 Sound Recorder"))
        self.importFileBtn.setText(_translate("mainWindow", " +  Import file"))
        self.selectedFileName.setText(_translate("mainWindow", "(none)"))
        self.removeSelectedBtn.setText(_translate("mainWindow", "Remove selected file"))
        self.audioFileList.setSortingEnabled(False)
        self.AudioTitle.setText(_translate("mainWindow", "Please select a audio file."))
        self.speech2text.setText(_translate("mainWindow", "(Audio text will show in here if it is supported)"))
        self.hoverSecond.setText(_translate("mainWindow", "00:00:00.00"))
        self.tap.setTabText(self.tap.indexOf(self.mainPage), _translate("mainWindow", "Welcome"))
        self.recordTimeTitle.setText(_translate("mainWindow", "Time:"))
        self.recordTime.setText(_translate("mainWindow", "00:00:00.00"))
        self.label_15.setText(_translate("mainWindow", "For resuming, click one more time \"pause\" to resume."))
        self.tap.setTabText(self.tap.indexOf(self.Recording), _translate("mainWindow", "Recording"))
        self.audioInfoTitle.setText(_translate("mainWindow", "Audio information:"))
        self.label_9.setText(_translate("mainWindow", "File name:"))
        self.label_11.setText(_translate("mainWindow", "Duration:"))
        self.editingTitle.setText(_translate("mainWindow", "Editing:"))
        self.label_13.setText(_translate("mainWindow", "Starting Time:"))
        self.label_14.setText(_translate("mainWindow", "Ending Time:"))
        self.editingTitle_2.setText(_translate("mainWindow", "Message:"))
        self.cutAndSaveBtn.setText(_translate("mainWindow", "Cut and save"))
        self.label_7.setText(_translate("mainWindow", "For Overwriting: Please record a new audio or import another audio first"))
        self.label_8.setText(_translate("mainWindow", "It will overwriting from starting time"))
        self.editRecordTime.setText(_translate("mainWindow", "00:00:00.00"))
        self.overwriteBtn.setText(_translate("mainWindow", "Overwriting"))
        self.importCoverFIle.setText(_translate("mainWindow", "Import"))
        self.owTips.setText(_translate("mainWindow", "[No audio rcord now]"))
        self.tap.setTabText(self.tap.indexOf(self.Editing), _translate("mainWindow", "Editing"))
        self.enc_message.setText(_translate("mainWindow", "Message:"))
        self.audioInfoTitle_2.setText(_translate("mainWindow", "Change Pitch:"))
        self.pitchChange.setText(_translate("mainWindow", "Change"))
        self.label_3.setText(_translate("mainWindow", "Noise remove:"))
        self.noiseRemoveBtn.setText(_translate("mainWindow", "Process"))
        self.tap.setTabText(self.tap.indexOf(self.enhancement), _translate("mainWindow", "Enhancements"))
        self.label.setText(_translate("mainWindow", "Aduio Driver:"))
        self.label_2.setText(_translate("mainWindow", "Saving Location:"))
        self.SavingPathEdit.setText(_translate("mainWindow", "Edit Path"))
        self.tap.setTabText(self.tap.indexOf(self.Setting), _translate("mainWindow", "Setting"))
        self.currentTime.setText(_translate("mainWindow", "00:00:00.00"))
        self.endTime.setText(_translate("mainWindow", "00:00:00"))
        self.label_5.setText(_translate("mainWindow", "Speed"))
        self.speedControl.setItemText(0, _translate("mainWindow", "0.25x"))
        self.speedControl.setItemText(1, _translate("mainWindow", "0.5x"))
        self.speedControl.setItemText(2, _translate("mainWindow", "1.0x"))
        self.speedControl.setItemText(3, _translate("mainWindow", "1.5x"))
        self.speedControl.setItemText(4, _translate("mainWindow", "2.0x"))
        self.speedControl.setItemText(5, _translate("mainWindow", "4.0x"))
        self.playerMessage.setText(_translate("mainWindow", "Message:"))
import UI.cover_rc
import UI.icon_rc
